apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: docker-username/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "flaskr/__init__.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: REDIS_HOST
          value: "redis"
        - name: SCRAPER_URL
          value: "http://scraper-service:5001/trigger_scrape"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
